// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEY-PEt9zUvad0TG2lNpGjJDb9Lry7aXM',
    appId: '1:1025648431140:web:88a6294a7b5d7c212f88b1',
    messagingSenderId: '1025648431140',
    projectId: 'quizapp-70d6c',
    authDomain: 'quizapp-70d6c.firebaseapp.com',
    storageBucket: 'quizapp-70d6c.appspot.com',
    measurementId: 'G-LWJ5SXJ0YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdrivDDDW8cWJHPfiJBp7M1-8NHIl-kHA',
    appId: '1:1025648431140:android:bb70494255d58f032f88b1',
    messagingSenderId: '1025648431140',
    projectId: 'quizapp-70d6c',
    storageBucket: 'quizapp-70d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8S567Ib-fVZwwOVCBCiF1OWSGvEukOI4',
    appId: '1:1025648431140:ios:560f59653552267f2f88b1',
    messagingSenderId: '1025648431140',
    projectId: 'quizapp-70d6c',
    storageBucket: 'quizapp-70d6c.appspot.com',
    iosClientId: '1025648431140-64tl4pf5n5o135t5sn1cbebj5lcfcrae.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
